#!/bin/bash
# Set the password for user sebadmin in files/settings.yml


    # This can be changed, using 'mkpasswd -m SHA-512 $password'

# Don't tolerate errors
set -e

# Check our arguments
if [ $# != 1 ]
then
  echo "Usage: $(basename $0) password"
  exit 1
fi

# Encrypt password
echo "Encrypting password ..."
pass="$1"
crypt_pass=$(mkpasswd -m SHA-512 "${pass}")

# Set the password in settings.yml
echo "Setting password in files/settings.yml ..."
tmp=$(tempfile)
cat files/settings.yml | sed "/sebadmin/,/sshkeys/{
    s%password: .*$%password: '${crypt_pass}'%
}" > $tmp
cp $tmp files/settings.yml
rm $tmp

echo "All done."
