#!/bin/bash
# Parse a jinja2 template and save to a temp file

# Don't tolerate errors
set -e

# Check our arguments
if [ $# != 2 ]
then
  echo "Usage: $(basename $0) template yaml-data"
  exit 1
fi

# Get our arguments
TEMPLATE="$1"
DATA="$2"

# Parse the template
TMP=$(tempfile)
jinja2 --format=yaml ${TEMPLATE} ${DATA} > ${TMP}
echo ${TMP}
