#!/bin/bash
# Parse a jinja2 template and run it as a script

# Don't tolerate errors
set -e

# Check our arguments
if [ $# != 2 ]
then
  echo "Usage: $(basename $0) script-template yaml-data"
  exit 1
fi

# Get our arguments
SCRIPT="$1"
DATA="$2"

# Get the parsed template and run it
TMP=$(scripts/jinjize "$SCRIPT" "$DATA")
bash $TMP
rm $TMP
